### ISSUE TITLE
Null Object Reference mAgendaCalendarView.init(eventList, minDate, maxDate, Locale.getDefault(), mPickerController);

### ISSUE THREAD

**Issue by LeoJHarris** [Tibolte/AgendaCalendarView#9]
Using your simple example I am running into this issue when I return to the Fragment (not using the back button) that is running the CalendarView, this line of code is giving me the following error

 mAgendaCalendarView.init(eventList, minDate, maxDate, Locale.getDefault(), mPickerController);

rx.exceptions.OnErrorNotImplementedException: Attempt to invoke virtual method 'void com.github.tibolte.agendacalendarview.agenda.AgendaAdapter.updateEvents(java.util.List)' on a null object reference

**Comment by LeoJHarris** [comment]
Sorted this, AgendaCalendarView wasnt working in my fragment but fine in my activity

**Comment by Tibolte** [comment]
Could this be some restoreState problem?

**Comment by LeoJHarris** [comment]
Not entirely sure sorry.

**Comment by arkangelx** [comment]
Anyway had issues with multiple event loading on the same day?

**Comment by LeoJHarris** [comment]
No issues with event loading. The only issue I seem be having is when I make events for in the new year they dont load.


________________________________

**Comment by Tibolte** [comment]
Allright, is this null pointer exception resolved for you? If so, we can close that ticket. And you can create an issue about loading events for a new year. Let's not go in every direction here :)

**Comment by arkangelx** [comment]
I understand, you can close the ticket

**Comment by LeoJHarris** [comment]
This issue was resolved. Will open a new on the new year events not loading.

**Comment by arkangelx** [comment]
I sent an email prior to this with some code snippets? Will that work for you?

**Comment by Tibolte** [comment]
Didn't have time to check it yet, I'll try today.

**Comment by arkangelx** [comment]
Ok.thank and I have spent 3 days going thru your code without much success fixing it. Are you in the habit of looking thru peoples code or is that too laborious for you?

**Comment by arkangelx** [comment]
In the off chance that you would be able to have a look, in the drop box folder is the problem class, a fragment with about 70 lines

https://www.dropbox.com/sh/omddbhnx9baliwo/AACLa2DOojJaYCWdEbCuJmzJa?dl=0


the associated objects and classes are also there.

Thanks for your anticipated help.

Kind regards

**Comment by Tibolte** [comment]
That's not a habit for me, but I do sometimes! Thanks for providing the files!

**Comment by arkangelx** [comment]
I thought initially the problem could be my my code, but all I’m doing is reading a json file and giving it to jackson  object mapper. If the json is wrong jackson would tell me.. I thought it was something to do with the min and max dates etc but every combination i tried didn’t work. None of the events were loaded in the right positions. Its weird because your test project modified a bit by me as  POC shows 3 events loading 1 day after another but the catch is that they are dates in the future in december.

 As a fair exchange i will be writing module that pulls events from a web api and will raise a PR for u to approve. I have to admit your library is so cool so instead of removing it from my app, i’d hope you can fix it this weekend
Thank you for looking @ the code. I don’t mean to take the piss, but i ran out of options here.

**Comment by damian-reweda** [comment]
Hi! Unfortunately, I have the same issue:

NullPointerException: Attempt to invoke virtual method 'void com.github.tibolte.agendacalendarview.agenda.AgendaAdapter.updateEvents(java.util.List)' on a null object reference 

when I return to the Fragment that is running the CalendarView. It is really weird because If I use back button - everything is alright. If I use the back arrow on Toolbar I get an error.

This line of code:
mAgendaCalendarView.init(eventList, minDate, maxDate, Locale.getDefault(), mPickerController);

I read that it worked moving CalendarView to Activity but in my solution I have to implement it in Fragment.

Do you have any idea?
